name: Setup App
description: Setup App dependencies for testing and building

runs:
    using: 'composite'
    steps:
        - name: Install Linux packages
          if: runner.os == 'Linux'
          shell: bash
          run: |
              sudo apt update
              sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev gcc g++ upx

        - name: Install MacOS packages
          if: runner.os == 'macOS'
          run: |
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              brew install upx

        - name: Install UPX on Windows
          if: runner.os == 'Windows'
          uses: crazy-max/ghaction-upx@v3
          with:
              install-only: true

        - name: Setup Go 1.22.0
          uses: actions/setup-go@v5
          with:
              go-version: '1.22.0'

        - name: Setup Node.js '20.x'
          uses: actions/setup-node@v4
          with:
              node-version: '20.x'

        - name: Setup Yarn
          shell: bash
          run: |
              corepack enable
              corepack prepare yarn@stable --activate
              yarn set version 3.5.0

        - name: Setup app frontend
          shell: bash
          run: |
              cd frontend
              yarn install

        - name: Setup app Go
          shell: bash
          run: |
              go install github.com/magefile/mage
              mage -v bootstrap
