name: App build

on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: App core Setup
              uses: ./.github/actions/core-setup

            - name: Test app
              uses: ./.github/actions/app-test
    build:
        needs: test
        strategy:
            fail-fast: false
            matrix:
                build:
                    - name: app_build
                      platform: linux
                      arch: amd64
                      os: ubuntu-latest
                    - name: app_build
                      platform: windows
                      arch: amd64
                      os: windows-latest
                    - name: app_build
                      platform: darwin
                      arch: amd64
                      os: macos-latest
        runs-on: ${{ matrix.build.os }}
        steps:
            - uses: actions/checkout@v4

            - name: App core Setup
              uses: ./.github/actions/core-setup

            - name: Build app
              run: |
                  mage -v build:release

            - name: Set binary variables
              id: binary_variables
              shell: bash
              run: |
                  case "${{ runner.os }}" in
                    Linux)
                      export BINARY_SUFFIX=
                      mv -f "./build/bin/adrift-native" "./build/bin/adrift-native"
                      ;;
                    Windows)
                      export BINARY_SUFFIX=.exe
                      mv -f "./build/bin/adrift-native.exe" "./build/bin/adrift-native.exe"
                      ;;
                    macOS)
                      export BINARY_SUFFIX=
                      mv -f "./build/bin/Adrift Native.app/Contents/MacOS/Adrift Native" "./build/bin/adrift-native"
                      ;;
                  esac
                  export BINARY_FILENAME=adrift-native${BINARY_SUFFIX}
                  export RELEASE_VERSION=${{ github.ref_name }}
                  mage -v release:prepare
                  export RELEASE_FILENAME=adrift-native_${{ github.ref_name }}_${{ matrix.build.platform }}_${{ matrix.build.arch }}${BINARY_SUFFIX}
                  echo "::set-output name=RELEASE_FILENAME::${RELEASE_FILENAME}"

            - name: Upload binary artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.binary_variables.outputs.RELEASE_FILENAME }}
                  path: ./build/bin/${{ steps.binary_variables.outputs.RELEASE_FILENAME }}

    #
    # Release binaries to various platforms. E.g. FTP server, GitHub releases.
    #
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Go 1.22.0
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22.0'

            - name: Setup app Go
              shell: bash
              run: |
                  go install github.com/magefile/mage
                  mage -v bootstrap

            - name: Download binary artifacts
              uses: actions/download-artifact@v4
              with:
                  path: adrift-native
                  pattern: adrift-native-*
                  merge-multiple: true

            - name: Release to FTP
              uses: ./.github/actions/core-release-ftp
              with:
                  ftp_host: ${{ secrets.FTP_HOST }}
                  ftp_username: ${{ secrets.FTP_USERNAME }}
                  ftp_password: ${{ secrets.FTP_PASSWORD }}
                  ftp_path: ${{ secrets.FTP_PATH }}
                  local_path: ./adrift-native
                  release_version: ${{ github.ref_name }}

            - name: Release to GitHub via tagged-release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release v${{ github.ref_name }}
                  draft: true
                  prerelease: false
                  files: |
                      ./adrift-native/adrift-native_${{ github.ref_name }}_darwin_amd64
                      ./adrift-native/adrift-native_${{ github.ref_name }}_linux_amd64
                      ./adrift-native/adrift-native_${{ github.ref_name }}_windows_amd64.exe
