name: App build

on: [push, pull_request]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                go-version: [1.22.x]
                node-version: [20.x]
                build:
                    - name: appBuild
                      platform: linux/amd64
                      os: ubuntu-latest
                    - name: appBuild
                      platform: windows/amd64
                      os: windows-latest
                    - name: appBuild
                      platform: darwin/universal
                      os: macos-latest
        runs-on: ${{ matrix.build.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go ${{ matrix.go-version }}
              uses: actions/setup-go@v4

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate
                  yarn set version 3.5.0

            - name: Build frontend
              run: |
                  cd frontend
                  yarn install
                  yarn test:coverage
                  yarn build

            - name: Build app
              run: |
                  go install github.com/magefile/mage
                  mage -v bootstrap

            # - name: Upload Go binary
            #   uses: actions/upload-artifact@v2
            #   with:
            #     name: go-app
            #     path: path/to/go-app/your-go-binary
