name: Core setup

on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string

env:
    GO_VERSION: '1.22.0'
    NODE_VERSION: '20.x'

jobs:
    core_setup:
        runs-on: ${{ inputs.os }}
        steps:
            - name: Install Linux packages
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev gcc g++

            - name: Setup Go ${{ env.GO_VERSION }}
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GO_VERSION }}

            - name: Setup Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Setup Yarn
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate
                  yarn set version 3.5.0

            - name: Setup app frontend
              run: |
                  cd frontend
                  yarn install

            - name: Setup app Go
              run: |
                  go install github.com/magefile/mage
                  mage -v bootstrap
