name: Core test

on:
    workflow_call:

jobs:
    core_test:
        strategy:
            fail-fast: false
            matrix:
                go-version: [1.22.0]
                node-version: [20.x]
                build:
                    - name: core_test
                      platform: linux/amd64
                      os: ubuntu-latest
                    - name: core_test
                      platform: windows/amd64
                      os: windows-latest
                    - name: core_test
                      platform: darwin/universal
                      os: macos-latest
        runs-on: ${{ matrix.build.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/workflows/core-setup.yml
              with:
                  os: ${{ matrix.os }}

            - name: Test frontend
              run: |
                  cd frontend
                  yarn install
                  yarn test:coverage
                  yarn build

            - name: Test app
              run: |
                  mage -v test
                  mage -v build
