name: Core test

on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string

jobs:
    core_test:
        runs-on: ${{ inputs.os }}
        steps:
            - name: Setup app
              uses: ./.github/workflows/core-setup.yml
              with:
                  os: ${{ inputs.os }}

            - name: Test frontend
              run: |
                  cd frontend
                  yarn install
                  yarn test:coverage
                  yarn build

            - name: Test app
              run: |
                  mage -v test
                  mage -v build
