name: App test core

on:
    workflow_call:

jobs:
    core_test:
        strategy:
            fail-fast: false
            matrix:
                go-version: [1.22.0]
                node-version: [20.x]
                build:
                    - name: appBuild
                      platform: linux/amd64
                      os: ubuntu-latest
                    - name: appBuild
                      platform: windows/amd64
                      os: windows-latest
                    - name: appBuild
                      platform: darwin/universal
                      os: macos-latest
        runs-on: ${{ matrix.build.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install Linux packages
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev gcc g++

            - name: Setup Go ${{ matrix.go-version }}
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Yarn
              run: |
                  corepack enable
                  corepack prepare yarn@stable --activate
                  yarn set version 3.5.0

            - name: Test frontend
              run: |
                  cd frontend
                  yarn install
                  yarn test:coverage
                  yarn build

            - name: Test app
              run: |
                  go install github.com/magefile/mage
                  mage -v bootstrap
                  mage -v test
                  mage -v build
