name: App test

on:
    push:
        tags-ignore:
            - '[0-9]+.[0-9]+.[0-9]+'
        branches:
            - '**'
    pull_request:
        branches:
            - '*'

# env:
#     MATRIX_OS: ubuntu-latest windows-latest macos-latest

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                build:
                    - name: app_test
                      platform: linux/amd64
                      os: ubuntu-latest
                    - name: app_test
                      platform: windows/amd64
                      os: windows-latest
                    - name: app_test
                      platform: darwin/universal
                      os: macos-latest
        runs-on: ${{ matrix.build.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/core-setup

            - name: Test app
              uses: ./.github/actions/app-test
