name: App test

on:
    push:
        tags-ignore:
            - '[0-9]+.[0-9]+.[0-9]+'
        branches:
            - '**'
    pull_request:
        branches:
            - '*'

jobs:
    test:
        uses: ./.github/workflows/core-test.yml
